project_id = "rphztcqtfxxazfwfuzdx"

[functions.meal-search]
verify_jwt = false

[functions.google-calendar-auth]
verify_jwt = false

[functions.google-calendar-sync]
verify_jwt = false

[functions.scan-emails]
verify_jwt = false

[functions.scan-document]
verify_jwt = false

[functions.google-sheets-spending]
verify_jwt = false

[functions.scan-recipe]
verify_jwt = false
